runtime: go123
service: default

handlers:
  - url: /.*
    script: auto

entrypoint: go run cmd/main.go

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

env_variables:
  PORT: "8080"
  FIREBASE_PROJECT_ID: "chatapp-86ff1"
  FIREBASE_CREDENTIALS: "config/serviceAccountKey.json"